CREATE TABLE IF NOT EXISTS public.tbl_migrations_history
(
    "MigrationId" varchar(150) NOT NULL,
    "ProductVersion" varchar(32) NOT NULL,
    CONSTRAINT "PK_tbl_migrations_history" PRIMARY KEY ("MigrationId")
);

CREATE TABLE IF NOT EXISTS public.tbl_roles
(
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" varchar(256) NULL,
    "NormalizedName" varchar(256) NULL,
    "ConcurrencyStamp" text NULL,
    CONSTRAINT "PK_tbl_roles" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public.tbl_users
(
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "FullName" text NOT NULL,
    "CreatedAt" timestamptz NOT NULL DEFAULT now(),
    "UpdatedAt" timestamptz NOT NULL DEFAULT now(),
    "UserName" varchar(256) NULL,
    "NormalizedUserName" varchar(256) NULL,
    "Email" varchar(256) NULL,
    "NormalizedEmail" varchar(256) NULL,
    "EmailConfirmed" boolean NOT NULL DEFAULT TRUE,
    "PasswordHash" text NULL,
    "SecurityStamp" text NULL,
    "ConcurrencyStamp" text NULL,
    "PhoneNumber" text NULL,
    "PhoneNumberConfirmed" boolean NOT NULL DEFAULT FALSE,
    "TwoFactorEnabled" boolean NOT NULL DEFAULT FALSE,
    "LockoutEnd" timestamptz NULL,
    "LockoutEnabled" boolean NOT NULL DEFAULT TRUE,
    "AccessFailedCount" integer NOT NULL DEFAULT 0,
    CONSTRAINT "PK_tbl_users" PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public.tbl_restaurants
(
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "OwnerUserId" integer NOT NULL,
    "Name" varchar(120) NOT NULL,
    "Slug" varchar(120) NOT NULL,
    "BranchName" varchar(120) NULL,
    "Address" varchar(240) NULL,
    "LogoPath" varchar(512) NULL,
    "PrimaryColor" varchar(7) NULL,
    "SecondaryColor" varchar(7) NULL,
    "PaletteKey" varchar(80) NULL,
    "CurrencyCode" varchar(8) NOT NULL DEFAULT 'INR',
    "CreatedAt" timestamptz NOT NULL DEFAULT now(),
    "UpdatedAt" timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT "PK_tbl_restaurants" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_tbl_restaurants_tbl_users_OwnerUserId"
        FOREIGN KEY ("OwnerUserId")
        REFERENCES public.tbl_users ("Id")
        ON DELETE CASCADE,
    CONSTRAINT "CK_tbl_restaurants_Slug_Format"
        CHECK ("Slug" ~ '^[a-z0-9]+(-[a-z0-9]+)*$'),
    CONSTRAINT "CK_tbl_restaurants_PrimaryColor_Format"
        CHECK ("PrimaryColor" IS NULL OR "PrimaryColor" ~ '^#[0-9A-Fa-f]{6}$'),
    CONSTRAINT "CK_tbl_restaurants_SecondaryColor_Format"
        CHECK ("SecondaryColor" IS NULL OR "SecondaryColor" ~ '^#[0-9A-Fa-f]{6}$'),
    CONSTRAINT "CK_tbl_restaurants_CurrencyCode_Valid"
        CHECK ("CurrencyCode" IN ('INR', 'USD', 'EUR'))
);

CREATE TABLE IF NOT EXISTS public.tbl_menu_items
(
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "RestaurantId" integer NOT NULL,
    "Name" varchar(120) NOT NULL,
    "Price" numeric(10,2) NOT NULL,
    "Serves" integer NOT NULL DEFAULT 1,
    "Category" varchar(32) NOT NULL,
    "FoodType" varchar(16) NOT NULL,
    "Status" varchar(24) NOT NULL,
    "CreatedAt" timestamptz NOT NULL DEFAULT now(),
    "UpdatedAt" timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT "PK_tbl_menu_items" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_tbl_menu_items_tbl_restaurants_RestaurantId"
        FOREIGN KEY ("RestaurantId")
        REFERENCES public.tbl_restaurants ("Id")
        ON DELETE CASCADE,
    CONSTRAINT "CK_tbl_menu_items_Price_Positive"
        CHECK ("Price" > 0),
    CONSTRAINT "CK_tbl_menu_items_Serves_Positive"
        CHECK ("Serves" > 0),
    CONSTRAINT "CK_tbl_menu_items_Status_Valid"
        CHECK ("Status" IN ('Active', 'Inactive', 'OutOfStock')),
    CONSTRAINT "CK_tbl_menu_items_Category_Valid"
        CHECK ("Category" IN ('Starters', 'MainCourse', 'Curries', 'Meals', 'RiceAndBiryani', 'Breads', 'Beverages', 'Desserts')),
    CONSTRAINT "CK_tbl_menu_items_FoodType_Valid"
        CHECK ("FoodType" IN ('Veg', 'NonVeg'))
);

CREATE TABLE IF NOT EXISTS public.tbl_menu_item_images
(
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "MenuItemId" integer NOT NULL,
    "ImagePath" varchar(512) NOT NULL,
    "SortOrder" integer NOT NULL DEFAULT 0,
    "CreatedAt" timestamptz NOT NULL DEFAULT now(),
    "UpdatedAt" timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT "PK_tbl_menu_item_images" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_tbl_menu_item_images_tbl_menu_items_MenuItemId"
        FOREIGN KEY ("MenuItemId")
        REFERENCES public.tbl_menu_items ("Id")
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public.tbl_role_claims
(
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "RoleId" integer NOT NULL,
    "ClaimType" text NULL,
    "ClaimValue" text NULL,
    CONSTRAINT "PK_tbl_role_claims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_tbl_role_claims_tbl_roles_RoleId"
        FOREIGN KEY ("RoleId")
        REFERENCES public.tbl_roles ("Id")
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public.tbl_user_claims
(
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "ClaimType" text NULL,
    "ClaimValue" text NULL,
    CONSTRAINT "PK_tbl_user_claims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_tbl_user_claims_tbl_users_UserId"
        FOREIGN KEY ("UserId")
        REFERENCES public.tbl_users ("Id")
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public.tbl_user_logins
(
    "LoginProvider" text NOT NULL,
    "ProviderKey" text NOT NULL,
    "ProviderDisplayName" text NULL,
    "UserId" integer NOT NULL,
    CONSTRAINT "PK_tbl_user_logins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
    CONSTRAINT "FK_tbl_user_logins_tbl_users_UserId"
        FOREIGN KEY ("UserId")
        REFERENCES public.tbl_users ("Id")
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public.tbl_user_roles
(
    "UserId" integer NOT NULL,
    "RoleId" integer NOT NULL,
    CONSTRAINT "PK_tbl_user_roles" PRIMARY KEY ("UserId", "RoleId"),
    CONSTRAINT "FK_tbl_user_roles_tbl_users_UserId"
        FOREIGN KEY ("UserId")
        REFERENCES public.tbl_users ("Id")
        ON DELETE CASCADE,
    CONSTRAINT "FK_tbl_user_roles_tbl_roles_RoleId"
        FOREIGN KEY ("RoleId")
        REFERENCES public.tbl_roles ("Id")
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS public.tbl_user_tokens
(
    "UserId" integer NOT NULL,
    "LoginProvider" text NOT NULL,
    "Name" text NOT NULL,
    "Value" text NULL,
    CONSTRAINT "PK_tbl_user_tokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
    CONSTRAINT "FK_tbl_user_tokens_tbl_users_UserId"
        FOREIGN KEY ("UserId")
        REFERENCES public.tbl_users ("Id")
        ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS "RoleNameIndex"
    ON public.tbl_roles ("NormalizedName");

CREATE INDEX IF NOT EXISTS "EmailIndex"
    ON public.tbl_users ("NormalizedEmail");

CREATE UNIQUE INDEX IF NOT EXISTS "UserNameIndex"
    ON public.tbl_users ("NormalizedUserName");

CREATE INDEX IF NOT EXISTS "IX_tbl_restaurants_OwnerUserId"
    ON public.tbl_restaurants ("OwnerUserId");

CREATE UNIQUE INDEX IF NOT EXISTS "IX_tbl_restaurants_Slug"
    ON public.tbl_restaurants ("Slug");

CREATE INDEX IF NOT EXISTS "IX_tbl_menu_items_RestaurantId_Status"
    ON public.tbl_menu_items ("RestaurantId", "Status");

CREATE INDEX IF NOT EXISTS "IX_tbl_menu_item_images_MenuItemId_SortOrder"
    ON public.tbl_menu_item_images ("MenuItemId", "SortOrder");

CREATE INDEX IF NOT EXISTS "IX_tbl_role_claims_RoleId"
    ON public.tbl_role_claims ("RoleId");

CREATE INDEX IF NOT EXISTS "IX_tbl_user_claims_UserId"
    ON public.tbl_user_claims ("UserId");

CREATE INDEX IF NOT EXISTS "IX_tbl_user_logins_UserId"
    ON public.tbl_user_logins ("UserId");

CREATE INDEX IF NOT EXISTS "IX_tbl_user_roles_RoleId"
    ON public.tbl_user_roles ("RoleId");
