CREATE TABLE IF NOT EXISTS tbl_migrations_history (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK_tbl_migrations_history" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE tbl_restaurants (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "OwnerUserId" integer NOT NULL,
    "Name" character varying(120) NOT NULL,
    "Slug" character varying(120) NOT NULL,
    "BranchName" character varying(120),
    "Address" character varying(240),
    "LogoPath" character varying(512),
    "PrimaryColor" character varying(7),
    "SecondaryColor" character varying(7),
    "PaletteKey" character varying(80),
    "CurrencyCode" character varying(8) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_tbl_restaurants" PRIMARY KEY ("Id")
);

CREATE TABLE tbl_roles (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Name" character varying(256),
    "NormalizedName" character varying(256),
    "ConcurrencyStamp" text,
    CONSTRAINT "PK_tbl_roles" PRIMARY KEY ("Id")
);

CREATE TABLE tbl_users (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "FullName" text NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    "UserName" character varying(256),
    "NormalizedUserName" character varying(256),
    "Email" character varying(256),
    "NormalizedEmail" character varying(256),
    "EmailConfirmed" boolean NOT NULL,
    "PasswordHash" text,
    "SecurityStamp" text,
    "ConcurrencyStamp" text,
    "PhoneNumber" text,
    "PhoneNumberConfirmed" boolean NOT NULL,
    "TwoFactorEnabled" boolean NOT NULL,
    "LockoutEnd" timestamp with time zone,
    "LockoutEnabled" boolean NOT NULL,
    "AccessFailedCount" integer NOT NULL,
    CONSTRAINT "PK_tbl_users" PRIMARY KEY ("Id")
);

CREATE TABLE tbl_menu_items (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "RestaurantId" integer NOT NULL,
    "Name" character varying(120) NOT NULL,
    "Price" numeric(10,2) NOT NULL,
    "Category" character varying(32) NOT NULL,
    "FoodType" character varying(16) NOT NULL,
    "Status" character varying(24) NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_tbl_menu_items" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_tbl_menu_items_tbl_restaurants_RestaurantId" FOREIGN KEY ("RestaurantId") REFERENCES tbl_restaurants ("Id") ON DELETE CASCADE
);

CREATE TABLE tbl_role_claims (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "RoleId" integer NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_tbl_role_claims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_tbl_role_claims_tbl_roles_RoleId" FOREIGN KEY ("RoleId") REFERENCES tbl_roles ("Id") ON DELETE CASCADE
);

CREATE TABLE tbl_user_claims (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "UserId" integer NOT NULL,
    "ClaimType" text,
    "ClaimValue" text,
    CONSTRAINT "PK_tbl_user_claims" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_tbl_user_claims_tbl_users_UserId" FOREIGN KEY ("UserId") REFERENCES tbl_users ("Id") ON DELETE CASCADE
);

CREATE TABLE tbl_user_logins (
    "LoginProvider" text NOT NULL,
    "ProviderKey" text NOT NULL,
    "ProviderDisplayName" text,
    "UserId" integer NOT NULL,
    CONSTRAINT "PK_tbl_user_logins" PRIMARY KEY ("LoginProvider", "ProviderKey"),
    CONSTRAINT "FK_tbl_user_logins_tbl_users_UserId" FOREIGN KEY ("UserId") REFERENCES tbl_users ("Id") ON DELETE CASCADE
);

CREATE TABLE tbl_user_roles (
    "UserId" integer NOT NULL,
    "RoleId" integer NOT NULL,
    CONSTRAINT "PK_tbl_user_roles" PRIMARY KEY ("UserId", "RoleId"),
    CONSTRAINT "FK_tbl_user_roles_tbl_roles_RoleId" FOREIGN KEY ("RoleId") REFERENCES tbl_roles ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_tbl_user_roles_tbl_users_UserId" FOREIGN KEY ("UserId") REFERENCES tbl_users ("Id") ON DELETE CASCADE
);

CREATE TABLE tbl_user_tokens (
    "UserId" integer NOT NULL,
    "LoginProvider" text NOT NULL,
    "Name" text NOT NULL,
    "Value" text,
    CONSTRAINT "PK_tbl_user_tokens" PRIMARY KEY ("UserId", "LoginProvider", "Name"),
    CONSTRAINT "FK_tbl_user_tokens_tbl_users_UserId" FOREIGN KEY ("UserId") REFERENCES tbl_users ("Id") ON DELETE CASCADE
);

CREATE TABLE tbl_menu_item_images (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "MenuItemId" integer NOT NULL,
    "ImagePath" character varying(512) NOT NULL,
    "SortOrder" integer NOT NULL,
    "CreatedAt" timestamp with time zone NOT NULL,
    "UpdatedAt" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_tbl_menu_item_images" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_tbl_menu_item_images_tbl_menu_items_MenuItemId" FOREIGN KEY ("MenuItemId") REFERENCES tbl_menu_items ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_tbl_menu_item_images_MenuItemId_SortOrder" ON tbl_menu_item_images ("MenuItemId", "SortOrder");

CREATE INDEX "IX_tbl_menu_items_RestaurantId_Status" ON tbl_menu_items ("RestaurantId", "Status");

CREATE INDEX "IX_tbl_restaurants_OwnerUserId" ON tbl_restaurants ("OwnerUserId");

CREATE UNIQUE INDEX "IX_tbl_restaurants_Slug" ON tbl_restaurants ("Slug");

CREATE INDEX "IX_tbl_role_claims_RoleId" ON tbl_role_claims ("RoleId");

CREATE UNIQUE INDEX "RoleNameIndex" ON tbl_roles ("NormalizedName");

CREATE INDEX "IX_tbl_user_claims_UserId" ON tbl_user_claims ("UserId");

CREATE INDEX "IX_tbl_user_logins_UserId" ON tbl_user_logins ("UserId");

CREATE INDEX "IX_tbl_user_roles_RoleId" ON tbl_user_roles ("RoleId");

CREATE INDEX "EmailIndex" ON tbl_users ("NormalizedEmail");

CREATE UNIQUE INDEX "UserNameIndex" ON tbl_users ("NormalizedUserName");

INSERT INTO tbl_migrations_history ("MigrationId", "ProductVersion")
VALUES ('20260331053411_InitialCreate', '8.0.12');

COMMIT;

START TRANSACTION;

ALTER TABLE tbl_menu_items ADD "BranchScope" character varying(24) NOT NULL DEFAULT 'ThisBranchOnly';

INSERT INTO tbl_migrations_history ("MigrationId", "ProductVersion")
VALUES ('20260331054931_AddBranchScopeToMenuItems', '8.0.12');

COMMIT;

